package team.xenobyte.modern.module.impl;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import net.minecraft.client.Minecraft;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import team.xenobyte.modern.XenobyteModernClient;
import team.xenobyte.modern.bootstrap.BootstrapLog;
import team.xenobyte.modern.gui.BuilderScreen;
import team.xenobyte.modern.gui.ModuleMessageLog;
import team.xenobyte.modern.module.Category;
import team.xenobyte.modern.module.ModuleMode;
import team.xenobyte.modern.module.XenoModule;
import team.xenobyte.modern.module.setting.ModuleSetting;
import team.xenobyte.modern.render.RenderUtil;
import team.xenobyte.modern.render.WorldRenderContext;

public class BuilderModule extends XenoModule {
    private static final int MAX_PLAN_BLOCKS = 300_000;
    private static final int QUEUE_SCAN_BUDGET = 2_048;
    private static final int PREVIEW_LIMIT = 6_000;
    private static final int RETRY_DELAY_TICKS = 4;
    private static final int DRAFT_REFRESH_TICKS = 3;
    private static final Direction[] SUPPORT_ORDER = {
        Direction.DOWN, Direction.NORTH, Direction.SOUTH,
        Direction.WEST, Direction.EAST, Direction.UP
    };

    private final ModuleSetting shape = setting("Shape", ModuleSetting.choice("Shape", 0,
        "Floor", "HollowBox", "Disc", "Ring", "Sphere", "HollowSphere",
        "ZoneFill", "ZoneShell", "ZoneWalls", "Arena")
        .describe("Structure generated by the planner."));
    private final ModuleSetting anchor = setting("Anchor", ModuleSetting.choice("Anchor", 0,
        "Player", "Crosshair", "FirstZone")
        .describe("Origin used by non-zone structures."));
    private final ModuleSetting width = setting("Width", ModuleSetting.number("Width", 11.0D, 1.0D, 96.0D, 1.0D)
        .describe("X size for floors and boxes."));
    private final ModuleSetting length = setting("Length", ModuleSetting.number("Length", 11.0D, 1.0D, 96.0D, 1.0D)
        .describe("Z size for floors and boxes."));
    private final ModuleSetting height = setting("Height", ModuleSetting.number("Height", 6.0D, 1.0D, 64.0D, 1.0D)
        .describe("Y size for boxes and arena walls."));
    private final ModuleSetting radius = setting("Radius", ModuleSetting.number("Radius", 8.0D, 1.0D, 48.0D, 1.0D)
        .describe("Radius for circles, spheres and arenas."));
    private final ModuleSetting thickness = setting("Thickness", ModuleSetting.number("Thickness", 1.0D, 1.0D, 6.0D, 1.0D)
        .describe("Shell, ring or wall thickness."));
    private final ModuleSetting offsetY = setting("OffsetY", ModuleSetting.number("OffsetY", 0.0D, -32.0D, 64.0D, 1.0D)
        .describe("Vertical offset from the selected anchor."));
    private final ModuleSetting material = setting("Material", ModuleSetting.choice("Material", 0, "Held", "FirstHotbar")
        .describe("Held block or first block stack in the hotbar."));
    private final ModuleSetting perTick = setting("PlaceTick", ModuleSetting.number("PlaceTick", 8.0D, 1.0D, 64.0D, 1.0D)
        .describe("Maximum placement packets per client tick."));
    private final ModuleSetting reach = setting("Reach", ModuleSetting.number("Reach", 8.0D, 3.0D, 16.0D, 0.5D)
        .describe("Maximum eye-to-placement distance."));
    private final ModuleSetting autoSwap = setting("AutoSwap", ModuleSetting.bool("AutoSwap", true)
        .describe("Selects a matching hotbar block stack automatically."));
    private final ModuleSetting autoMove = setting("AutoMove", ModuleSetting.bool("AutoMove", false)
        .describe("Flies toward pending supported blocks when none are reachable."));
    private final ModuleSetting moveSpeed = setting("MoveSpeed", ModuleSetting.number("MoveSpeed", 0.8D, 0.1D, 2.0D, 0.1D)
        .describe("AutoMove motion speed."));
    private final ModuleSetting preview = setting("Preview", ModuleSetting.bool("Preview", true)
        .describe("Renders pending structure blocks through terrain."));
    private final ModuleSetting swing = setting("Swing", ModuleSetting.bool("Swing", false)
        .describe("Swings the hand for placement attempts."));
    private final ModuleSetting openEditor = setting("OpenBuilder", ModuleSetting.action("OpenBuilder", this::openEditor)
        .describe("Opens the dedicated structure editor."));
    private final ModuleSetting livePreview = setting("LivePreview", ModuleSetting.action("LivePreview", this::startDraftPreview)
        .describe("Starts a live pre-build preview that follows the selected anchor."));
    private final ModuleSetting lockPreview = setting("LockPreview", ModuleSetting.action("LockPreview", this::lockDraftPreview)
        .describe("Freezes the current pre-build preview so it can be inspected before building."));
    private final ModuleSetting rebuild = setting("BuildNow", ModuleSetting.action("BuildNow", this::startFromUi)
        .describe("Regenerates and starts the current structure plan."));
    private final ModuleSetting cancel = setting("Cancel", ModuleSetting.action("Cancel", this::cancelFromUi)
        .describe("Cancels the active build queue."));

    private final ArrayDeque<BlockPos> queue = new ArrayDeque<>();
    private final Set<BlockPos> pending = new LinkedHashSet<>();
    private final Map<BlockPos, Integer> retryAfter = new ConcurrentHashMap<>();
    private List<BlockPos> draftPositions = List.of();
    private DraftState draftState = DraftState.OFF;
    private Block draftBlock;
    private BlockPos draftAnchor;
    private String draftShape = "";
    private String draftSignature = "";
    private boolean draftTruncated;
    private int draftRefreshTicks;
    private Block plannedBlock;
    private BlockPos planAnchor;
    private int moduleTicks;
    private int plannedTotal;
    private int confirmed;
    private int lastPlaced;
    private int blockedCycles;
    private boolean planTruncated;
    private boolean generationOverflow;
    private boolean movementSnapshot;
    private boolean previousNoGravity;
    private boolean previousNoPhysics;
    private long lastLogNanos;
    private String buildState = "idle";

    public BuilderModule() {
        super("Builder", Category.WORLD, ModuleMode.TOGGLE);
    }

    @Override
    public List<ModuleSetting> menuSettings() {
        return settings().stream()
            .filter(setting -> setting.kind() == ModuleSetting.Kind.ACTION)
            .toList();
    }

    @Override
    public void onEnable(Minecraft client) {
        snapshotMovement(client);
        if (queue.isEmpty()) {
            if (!commitDraftPlan(client)) {
                buildPlan(client);
            }
        }
    }

    @Override
    public void onDisable(Minecraft client) {
        restoreMovement(client);
        lastPlaced = 0;
    }

    @Override
    public boolean wantsTickWhenDisabled() {
        return draftState == DraftState.LIVE;
    }

    @Override
    public boolean wantsWorldRenderWhenDisabled() {
        return preview.boolValue() && !draftPositions.isEmpty();
    }

    @Override
    public void onTick(Minecraft client) {
        if (client == null || client.player == null || client.level == null) {
            return;
        }
        moduleTicks++;
        if (draftState == DraftState.LIVE) {
            refreshDraftPreview(client, false);
        }
        if (!enabled()) {
            return;
        }
        if (client.gameMode == null || client.getConnection() == null) {
            return;
        }
        if (client.screen != null || queue.isEmpty() || plannedBlock == null) {
            if (queue.isEmpty()) {
                restoreMovement(client);
                if (plannedTotal > 0 && pending.isEmpty()) {
                    buildState = "complete";
                }
            }
            return;
        }

        int hotbarSlot = matchingBlockSlot(client, plannedBlock);
        if (hotbarSlot < 0) {
            message(client, "Missing hotbar material: " + plannedBlockId());
            buildState = "missing-material";
            restoreMovement(client);
            return;
        }
        selectHotbar(client, hotbarSlot);

        lastPlaced = 0;
        int scanned = 0;
        int queueSize = queue.size();
        BlockPos navigationTarget = null;
        double navigationScore = Double.MAX_VALUE;
        while (scanned < Math.min(QUEUE_SCAN_BUDGET, queueSize) && !queue.isEmpty()) {
            BlockPos pos = queue.removeFirst();
            scanned++;
            if (!pending.contains(pos)) {
                continue;
            }
            if (!client.level.hasChunkAt(pos)) {
                queue.addLast(pos);
                double distanceSq = client.player.position().distanceToSqr(Vec3.atCenterOf(pos));
                if (distanceSq < navigationScore) {
                    navigationScore = distanceSq;
                    navigationTarget = pos;
                }
                continue;
            }
            if (isConfirmed(client, pos)) {
                confirm(pos);
                continue;
            }
            queue.addLast(pos);
            Integer retryTick = retryAfter.get(pos);
            if (retryTick != null && retryTick > moduleTicks) {
                continue;
            }
            BlockHitResult hit = supportHit(client, pos);
            if (hit == null) {
                continue;
            }
            double distanceSq = client.player.getEyePosition(0.0F).distanceToSqr(hit.getLocation());
            if (distanceSq > reach.doubleValue() * reach.doubleValue()) {
                if (distanceSq < navigationScore) {
                    navigationScore = distanceSq;
                    navigationTarget = pos;
                }
                continue;
            }
            if (lastPlaced >= perTick.intValue()) {
                continue;
            }
            InteractionResult result = client.gameMode.useItemOn(client.player, InteractionHand.MAIN_HAND, hit);
            retryAfter.put(pos, moduleTicks + RETRY_DELAY_TICKS);
            if (result.consumesAction()) {
                lastPlaced++;
                if (swing.boolValue()) {
                    client.player.swing(InteractionHand.MAIN_HAND);
                }
            }
        }

        if (lastPlaced == 0) {
            blockedCycles++;
            if (autoMove.boolValue() && navigationTarget != null) {
                buildState = "moving";
                moveTowardBuildTarget(client, navigationTarget);
            } else {
                buildState = navigationTarget == null ? "waiting-support" : "out-of-reach";
                restoreMovement(client);
                if (navigationTarget == null && (blockedCycles == 20 || blockedCycles % 100 == 0)) {
                    message(client, "No supported placement face; use Crosshair anchor against an existing block");
                }
            }
        } else {
            blockedCycles = 0;
            buildState = "placing";
            restoreMovement(client);
        }
        log("tick", "pending=" + pending.size()
            + ", confirmed=" + confirmed + "/" + plannedTotal
            + ", scanned=" + scanned
            + ", placed=" + lastPlaced
            + ", blocked=" + blockedCycles
            + ", material=" + plannedBlockId());
    }

    public void startFromUi() {
        Minecraft client = Minecraft.getInstance();
        if (client == null) {
            return;
        }
        if (!commitDraftPlan(client)) {
            buildPlan(client);
        }
        if (!enabled() && !queue.isEmpty()) {
            setEnabled(client, true);
        }
        XenobyteModernClient.MODULES.saveConfig();
    }

    public void cancelFromUi() {
        Minecraft client = Minecraft.getInstance();
        clearPlan();
        clearDraftPreview();
        buildState = "cancelled";
        restoreMovement(client);
        message(client, "Build cancelled");
        XenobyteModernClient.MODULES.saveConfig();
    }

    public void startDraftPreview() {
        Minecraft client = Minecraft.getInstance();
        if (client == null || client.player == null || client.level == null) {
            return;
        }
        if (!preview.boolValue()) {
            preview.setFromString("1");
        }
        draftState = DraftState.LIVE;
        draftSignature = "";
        draftRefreshTicks = 0;
        refreshDraftPreview(client, true);
        if (!draftPositions.isEmpty()) {
            buildState = "preview-live";
            message(client, "Live preview started; aim the crosshair, then press LOCK");
        }
        XenobyteModernClient.MODULES.saveConfig();
    }

    public void lockDraftPreview() {
        Minecraft client = Minecraft.getInstance();
        if (client == null || client.player == null || client.level == null) {
            return;
        }
        if (draftState == DraftState.OFF) {
            draftState = DraftState.LIVE;
        }
        refreshDraftPreview(client, true);
        if (draftPositions.isEmpty()) {
            message(client, "Preview anchor is unavailable");
            return;
        }
        draftState = DraftState.LOCKED;
        buildState = "preview-locked";
        message(client, "Preview locked: " + draftPositions.size() + " blocks at "
            + (draftAnchor == null ? "zones" : draftAnchor.toShortString()));
        XenobyteModernClient.MODULES.saveConfig();
    }

    public void openEditor() {
        Minecraft client = Minecraft.getInstance();
        if (client == null) {
            return;
        }
        client.setScreen(new BuilderScreen(this, client.screen));
    }

    private void buildPlan(Minecraft client) {
        StructureDraft structure = createStructure(client, true);
        if (structure != null) {
            installPlan(client, structure);
        }
    }

    private StructureDraft createStructure(Minecraft client, boolean notifyFailure) {
        DraftContext context = resolveDraftContext(client, notifyFailure);
        if (context == null) {
            return null;
        }
        LinkedHashSet<BlockPos> generated = new LinkedHashSet<>();
        generationOverflow = false;
        if (context.shape().startsWith("Zone")) {
            generateZones(client, context.shape(), generated);
        } else {
            generateShape(context.shape(), context.anchor(), generated);
        }
        return new StructureDraft(List.copyOf(generated), context.block(), context.anchor(), context.shape(), generationOverflow);
    }

    private DraftContext resolveDraftContext(Minecraft client, boolean notifyFailure) {
        if (client == null || client.player == null || client.level == null) {
            return null;
        }
        Block selected = selectedMaterial(client);
        if (selected == null) {
            if (notifyFailure) {
                message(client, "Hold a placeable block or enable FirstHotbar material");
            }
            return null;
        }
        String selectedShape = shape.choiceValue();
        BlockPos origin;
        if (selectedShape.startsWith("Zone")) {
            List<SelectedZoneRegistry.Zone> zones = SelectedZoneRegistry.snapshot(client.level.dimension());
            if (zones.isEmpty()) {
                if (notifyFailure) {
                    message(client, "No selected zones are available");
                }
                return null;
            }
            origin = zones.get(0).min();
        } else {
            origin = resolveAnchor(client);
            if (origin == null) {
                if (notifyFailure) {
                    message(client, "Builder anchor is unavailable");
                }
                return null;
            }
        }
        ResourceLocation blockId = BuiltInRegistries.BLOCK.getKey(selected);
        String signature = selectedShape + '|' + origin.asLong() + '|'
            + (blockId == null ? "unknown" : blockId.toString()) + '|'
            + width.intValue() + '|' + length.intValue() + '|' + height.intValue() + '|'
            + radius.intValue() + '|' + thickness.intValue() + '|' + offsetY.intValue() + '|'
            + SelectedZoneRegistry.version();
        return new DraftContext(selected, origin.immutable(), selectedShape, signature);
    }

    private void refreshDraftPreview(Minecraft client, boolean force) {
        if (!force && draftRefreshTicks-- > 0) {
            return;
        }
        draftRefreshTicks = DRAFT_REFRESH_TICKS;
        DraftContext context = resolveDraftContext(client, false);
        if (context == null) {
            // Keep the last valid crosshair anchor while the cursor briefly points at empty sky.
            return;
        }
        if (!force && context.signature().equals(draftSignature)) {
            return;
        }
        StructureDraft structure = createStructure(client, false);
        if (structure == null) {
            return;
        }
        draftPositions = structure.positions();
        draftBlock = structure.block();
        draftAnchor = structure.anchor();
        draftShape = structure.shape();
        draftSignature = context.signature();
        draftTruncated = structure.truncated();
    }

    private boolean commitDraftPlan(Minecraft client) {
        if (draftState == DraftState.OFF || draftPositions.isEmpty()) {
            return false;
        }
        if (draftState == DraftState.LIVE) {
            refreshDraftPreview(client, true);
        }
        if (draftPositions.isEmpty() || draftBlock == null) {
            return false;
        }
        StructureDraft structure = new StructureDraft(
            List.copyOf(draftPositions), draftBlock, draftAnchor, draftShape, draftTruncated);
        installPlan(client, structure);
        clearDraftPreview();
        return true;
    }

    private void installPlan(Minecraft client, StructureDraft structure) {
        clearPlan();
        plannedBlock = structure.block();
        planAnchor = structure.anchor();
        List<BlockPos> ordered = structure.positions().stream()
            .filter(pos -> !client.level.hasChunkAt(pos) || !client.level.getBlockState(pos).is(structure.block()))
            .sorted(Comparator
                .comparingInt((BlockPos pos) -> pos.getY())
                .thenComparingDouble(pos -> pos.distSqr(client.player.blockPosition()))
                .thenComparingInt(pos -> pos.getX())
                .thenComparingInt(pos -> pos.getZ()))
            .limit(MAX_PLAN_BLOCKS)
            .toList();
        planTruncated = structure.truncated() || structure.positions().size() > MAX_PLAN_BLOCKS;
        pending.addAll(ordered);
        queue.addAll(ordered);
        plannedTotal = ordered.size();
        confirmed = 0;
        blockedCycles = 0;
        retryAfter.clear();
        buildState = ordered.isEmpty() ? "complete" : "ready";
        message(client, "Planned " + plannedTotal + " blocks: " + structure.shape()
            + " / " + plannedBlockId() + (planTruncated ? " (truncated)" : ""));
        BootstrapLog.info("Builder plan: shape=" + structure.shape()
            + ", blocks=" + plannedTotal
            + ", generated=" + structure.positions().size()
            + ", material=" + plannedBlockId()
            + ", anchor=" + (planAnchor == null ? "zones" : planAnchor.toShortString())
            + ", truncated=" + planTruncated);
    }

    private void generateZones(Minecraft client, String selectedShape, Set<BlockPos> output) {
        List<SelectedZoneRegistry.Zone> zones = SelectedZoneRegistry.snapshot(client.level.dimension());
        for (SelectedZoneRegistry.Zone zone : zones) {
            for (int x = zone.min().getX(); x <= zone.max().getX(); x++) {
                for (int y = zone.min().getY(); y <= zone.max().getY(); y++) {
                    for (int z = zone.min().getZ(); z <= zone.max().getZ(); z++) {
                        boolean xEdge = x - zone.min().getX() < thickness.intValue()
                            || zone.max().getX() - x < thickness.intValue();
                        boolean yEdge = y - zone.min().getY() < thickness.intValue()
                            || zone.max().getY() - y < thickness.intValue();
                        boolean zEdge = z - zone.min().getZ() < thickness.intValue()
                            || zone.max().getZ() - z < thickness.intValue();
                        boolean include = switch (selectedShape) {
                            case "ZoneShell" -> xEdge || yEdge || zEdge;
                            case "ZoneWalls" -> xEdge || zEdge;
                            default -> true;
                        };
                        if (include) {
                            addPlanned(output, new BlockPos(x, y, z));
                        }
                    }
                }
            }
        }
    }

    private void generateShape(String selectedShape, BlockPos origin, Set<BlockPos> output) {
        switch (selectedShape) {
            case "HollowBox" -> generateBox(origin, output, true);
            case "Disc" -> generateDisc(origin, output, false);
            case "Ring" -> generateDisc(origin, output, true);
            case "Sphere" -> generateSphere(origin, output, false);
            case "HollowSphere" -> generateSphere(origin, output, true);
            case "Arena" -> generateArena(origin, output);
            default -> generateFloor(origin, output);
        }
    }

    private void generateFloor(BlockPos origin, Set<BlockPos> output) {
        int minX = origin.getX() - width.intValue() / 2;
        int minZ = origin.getZ() - length.intValue() / 2;
        for (int dx = 0; dx < width.intValue(); dx++) {
            for (int dz = 0; dz < length.intValue(); dz++) {
                addPlanned(output, new BlockPos(minX + dx, origin.getY(), minZ + dz));
            }
        }
    }

    private void generateBox(BlockPos origin, Set<BlockPos> output, boolean hollow) {
        int minX = origin.getX() - width.intValue() / 2;
        int minZ = origin.getZ() - length.intValue() / 2;
        int shell = thickness.intValue();
        for (int dx = 0; dx < width.intValue(); dx++) {
            for (int dy = 0; dy < height.intValue(); dy++) {
                for (int dz = 0; dz < length.intValue(); dz++) {
                    boolean edge = dx < shell || width.intValue() - 1 - dx < shell
                        || dy < shell || height.intValue() - 1 - dy < shell
                        || dz < shell || length.intValue() - 1 - dz < shell;
                    if (!hollow || edge) {
                        addPlanned(output, new BlockPos(minX + dx, origin.getY() + dy, minZ + dz));
                    }
                }
            }
        }
    }

    private void generateDisc(BlockPos origin, Set<BlockPos> output, boolean ring) {
        int r = radius.intValue();
        int inner = Math.max(0, r - thickness.intValue());
        int outerSq = r * r;
        int innerSq = inner * inner;
        for (int dx = -r; dx <= r; dx++) {
            for (int dz = -r; dz <= r; dz++) {
                int distanceSq = dx * dx + dz * dz;
                if (distanceSq <= outerSq && (!ring || distanceSq >= innerSq)) {
                    addPlanned(output, origin.offset(dx, 0, dz));
                }
            }
        }
    }

    private void generateSphere(BlockPos origin, Set<BlockPos> output, boolean hollow) {
        int r = radius.intValue();
        int inner = Math.max(0, r - thickness.intValue());
        int outerSq = r * r;
        int innerSq = inner * inner;
        BlockPos center = origin.above(r);
        for (int dx = -r; dx <= r; dx++) {
            for (int dy = -r; dy <= r; dy++) {
                for (int dz = -r; dz <= r; dz++) {
                    int distanceSq = dx * dx + dy * dy + dz * dz;
                    if (distanceSq <= outerSq && (!hollow || distanceSq >= innerSq)) {
                        addPlanned(output, center.offset(dx, dy, dz));
                    }
                }
            }
        }
    }

    private void generateArena(BlockPos origin, Set<BlockPos> output) {
        int r = radius.intValue();
        int wall = thickness.intValue();
        int inner = Math.max(0, r - wall);
        for (int dx = -r; dx <= r; dx++) {
            for (int dz = -r; dz <= r; dz++) {
                int distanceSq = dx * dx + dz * dz;
                if (distanceSq <= r * r) {
                    addPlanned(output, origin.offset(dx, 0, dz));
                }
                boolean wallBand = distanceSq <= r * r && distanceSq >= inner * inner;
                boolean gate = (Math.abs(dx) <= 1 && Math.abs(dz) >= r - wall - 1)
                    || (Math.abs(dz) <= 1 && Math.abs(dx) >= r - wall - 1);
                if (!wallBand) {
                    continue;
                }
                for (int y = 1; y < height.intValue(); y++) {
                    if (!gate || y >= 4) {
                        addPlanned(output, origin.offset(dx, y, dz));
                    }
                }
            }
        }
        int marker = Math.max(1, wall);
        for (int x = -marker; x <= marker; x++) {
            addPlanned(output, origin.offset(x, 1, 0));
        }
        for (int z = -marker; z <= marker; z++) {
            addPlanned(output, origin.offset(0, 1, z));
        }
    }

    private void addPlanned(Set<BlockPos> output, BlockPos pos) {
        if (output.size() >= MAX_PLAN_BLOCKS) {
            generationOverflow = true;
            return;
        }
        output.add(pos.immutable());
    }

    private BlockPos resolveAnchor(Minecraft client) {
        BlockPos base;
        switch (anchor.choiceValue()) {
            case "Crosshair" -> {
                HitResult hit = client.hitResult;
                if (!(hit instanceof BlockHitResult blockHit) || hit.getType() != HitResult.Type.BLOCK) {
                    return null;
                }
                base = blockHit.getBlockPos().relative(blockHit.getDirection());
            }
            case "FirstZone" -> {
                List<SelectedZoneRegistry.Zone> zones = SelectedZoneRegistry.snapshot(client.level.dimension());
                if (zones.isEmpty()) {
                    return null;
                }
                base = zones.get(0).min();
            }
            default -> base = new BlockPos(Mth.floor(client.player.getX()), Mth.floor(client.player.getY()) - 1,
                Mth.floor(client.player.getZ()));
        }
        return base.above(offsetY.intValue()).immutable();
    }

    private Block selectedMaterial(Minecraft client) {
        if ("Held".equals(material.choiceValue())) {
            ItemStack held = client.player.getMainHandItem();
            if (held.getItem() instanceof BlockItem blockItem) {
                return blockItem.getBlock();
            }
            return autoSwap.boolValue() ? firstHotbarBlock(client) : null;
        }
        return firstHotbarBlock(client);
    }

    private Block firstHotbarBlock(Minecraft client) {
        for (int slot = 0; slot < 9; slot++) {
            ItemStack stack = client.player.getInventory().items.get(slot);
            if (!stack.isEmpty() && stack.getItem() instanceof BlockItem blockItem) {
                return blockItem.getBlock();
            }
        }
        return null;
    }

    private int matchingBlockSlot(Minecraft client, Block block) {
        int selected = client.player.getInventory().selected;
        if (slotContains(client, selected, block)) {
            return selected;
        }
        if (!autoSwap.boolValue()) {
            return -1;
        }
        for (int slot = 0; slot < 9; slot++) {
            if (slotContains(client, slot, block)) {
                return slot;
            }
        }
        return -1;
    }

    private boolean slotContains(Minecraft client, int slot, Block block) {
        if (slot < 0 || slot >= 9 || slot >= client.player.getInventory().items.size()) {
            return false;
        }
        ItemStack stack = client.player.getInventory().items.get(slot);
        return !stack.isEmpty() && stack.getItem() instanceof BlockItem blockItem && blockItem.getBlock() == block;
    }

    private void selectHotbar(Minecraft client, int slot) {
        if (slot == client.player.getInventory().selected) {
            return;
        }
        client.player.getInventory().selected = slot;
        client.getConnection().send(new ServerboundSetCarriedItemPacket(slot));
    }

    private BlockHitResult supportHit(Minecraft client, BlockPos target) {
        BlockState targetState = client.level.getBlockState(target);
        if (!targetState.isAir() && !targetState.canBeReplaced()) {
            return null;
        }
        for (Direction direction : SUPPORT_ORDER) {
            BlockPos support = target.relative(direction);
            BlockState supportState = client.level.getBlockState(support);
            if (supportState.isAir() || supportState.getCollisionShape(client.level, support).isEmpty()) {
                continue;
            }
            Direction face = direction.getOpposite();
            Vec3 location = Vec3.atCenterOf(support).add(
                face.getStepX() * 0.5D,
                face.getStepY() * 0.5D,
                face.getStepZ() * 0.5D
            );
            return new BlockHitResult(location, face, support, false);
        }
        return null;
    }

    private boolean isConfirmed(Minecraft client, BlockPos pos) {
        return plannedBlock != null && client.level.getBlockState(pos).is(plannedBlock);
    }

    private void confirm(BlockPos pos) {
        if (pending.remove(pos)) {
            confirmed++;
        }
        retryAfter.remove(pos);
        if (pending.isEmpty() && plannedTotal > 0) {
            message(Minecraft.getInstance(), "Build complete: " + confirmed + " blocks");
            BootstrapLog.info("Builder completed: blocks=" + confirmed + ", material=" + plannedBlockId());
        }
    }

    private void moveTowardBuildTarget(Minecraft client, BlockPos target) {
        snapshotMovement(client);
        client.player.noPhysics = true;
        client.player.setNoGravity(true);
        Vec3 destination = Vec3.atCenterOf(target).add(0.0D, 2.0D, 0.0D);
        Vec3 delta = destination.subtract(client.player.position());
        if (delta.lengthSqr() < 0.04D) {
            client.player.setDeltaMovement(Vec3.ZERO);
            return;
        }
        double amount = Math.min(moveSpeed.doubleValue(), delta.length());
        client.player.setDeltaMovement(delta.normalize().scale(amount));
        client.player.setOnGround(false);
        client.player.fallDistance = 0.0F;
    }

    private void snapshotMovement(Minecraft client) {
        if (movementSnapshot || client == null || client.player == null) {
            return;
        }
        previousNoGravity = client.player.isNoGravity();
        previousNoPhysics = client.player.noPhysics;
        movementSnapshot = true;
    }

    private void restoreMovement(Minecraft client) {
        if (!movementSnapshot || client == null || client.player == null) {
            return;
        }
        client.player.setNoGravity(previousNoGravity);
        client.player.noPhysics = previousNoPhysics;
        movementSnapshot = false;
    }

    private void clearPlan() {
        queue.clear();
        pending.clear();
        retryAfter.clear();
        plannedTotal = 0;
        confirmed = 0;
        lastPlaced = 0;
        blockedCycles = 0;
        planTruncated = false;
    }

    private void clearDraftPreview() {
        draftPositions = List.of();
        draftState = DraftState.OFF;
        draftBlock = null;
        draftAnchor = null;
        draftShape = "";
        draftSignature = "";
        draftTruncated = false;
        draftRefreshTicks = 0;
    }

    @Override
    public void onWorldRender(WorldRenderContext context) {
        if (!preview.boolValue()) {
            return;
        }
        if (!draftPositions.isEmpty()) {
            List<AABB> boxes = draftPositions.stream().limit(PREVIEW_LIMIT).map(AABB::new).toList();
            int fillColor = draftState == DraftState.LOCKED ? 0x20ffd65a : 0x1855d6ff;
            int outlineColor = draftState == DraftState.LOCKED ? 0xccffd65a : 0xaa55d6ff;
            RenderUtil.drawFilledBoxesImmediate(context, boxes, fillColor);
            RenderUtil.drawBoxesImmediate(context, boxes, outlineColor);
            return;
        }
        if (!pending.isEmpty()) {
            List<AABB> boxes = pending.stream().limit(PREVIEW_LIMIT).map(AABB::new).toList();
            RenderUtil.drawFilledBoxesImmediate(context, boxes, 0x1855d6ff);
            RenderUtil.drawBoxesImmediate(context, boxes, 0xaa55d6ff);
        }
    }

    private void message(Minecraft client, String text) {
        ModuleMessageLog.push("Builder", text);
        if (client != null && client.player != null) {
            client.player.displayClientMessage(Component.literal("Builder: " + text), true);
        }
    }

    private void log(String phase, String details) {
        long now = System.nanoTime();
        if (now - lastLogNanos < 2_000_000_000L) {
            return;
        }
        lastLogNanos = now;
        BootstrapLog.info("Builder " + phase + ": " + details);
    }

    private String plannedBlockId() {
        if (plannedBlock == null) {
            return "none";
        }
        ResourceLocation id = BuiltInRegistries.BLOCK.getKey(plannedBlock);
        return id == null ? "unknown" : id.toString();
    }

    public String shapeValue() {
        return shape.choiceValue();
    }

    public String anchorValue() {
        return anchor.choiceValue();
    }

    public void cycleShape(int direction) {
        shape.adjust(direction);
    }

    public void cycleAnchor(int direction) {
        anchor.adjust(direction);
    }

    public void cycleMaterial(int direction) {
        material.adjust(direction);
    }

    public int settingInt(String name) {
        ModuleSetting selected = editableSetting(name);
        return selected == null ? 0 : selected.intValue();
    }

    public String settingDisplay(String name) {
        ModuleSetting selected = editableSetting(name);
        return selected == null ? "?" : selected.displayValue();
    }

    public void adjustSetting(String name, int direction) {
        ModuleSetting selected = editableSetting(name);
        if (selected != null) {
            selected.adjust(direction);
        }
    }

    public void setSetting(String name, String value) {
        ModuleSetting selected = editableSetting(name);
        if (selected != null) {
            selected.setFromString(value);
        }
    }

    private ModuleSetting editableSetting(String name) {
        return switch (name) {
            case "Width" -> width;
            case "Length" -> length;
            case "Height" -> height;
            case "Radius" -> radius;
            case "Thickness" -> thickness;
            case "OffsetY" -> offsetY;
            case "PlaceTick" -> perTick;
            case "Reach" -> reach;
            case "MoveSpeed" -> moveSpeed;
            default -> null;
        };
    }

    public boolean previewEnabled() {
        return preview.boolValue();
    }

    public void togglePreview() {
        preview.click(0);
    }

    public boolean autoMoveEnabled() {
        return autoMove.boolValue();
    }

    public void toggleAutoMove() {
        autoMove.click(0);
    }

    public boolean autoSwapEnabled() {
        return autoSwap.boolValue();
    }

    public void toggleAutoSwap() {
        autoSwap.click(0);
    }

    public boolean swingEnabled() {
        return swing.boolValue();
    }

    public void toggleSwing() {
        swing.click(0);
    }

    public int pendingCount() {
        return pending.size();
    }

    public int plannedCount() {
        return plannedTotal;
    }

    public String draftStateValue() {
        return draftState.name();
    }

    public int draftCount() {
        return draftPositions.size();
    }

    public String buildStateValue() {
        return buildState;
    }

    public String materialValue() {
        return material.choiceValue();
    }

    public EditorPreview editorPreview(Minecraft client) {
        Block displayBlock = null;
        if (client != null && client.player != null) {
            displayBlock = selectedMaterial(client);
        }
        if (displayBlock == null) {
            displayBlock = draftBlock != null ? draftBlock : plannedBlock;
        }

        ItemStack stack = displayBlock == null ? ItemStack.EMPTY : new ItemStack(displayBlock);
        ResourceLocation id = displayBlock == null ? null : BuiltInRegistries.BLOCK.getKey(displayBlock);
        String materialId = id == null ? "hold a block" : id.toString();
        String selectedShape = shape.choiceValue();
        int actualX;
        int actualY;
        int actualZ;
        int zoneCount = 0;
        if (selectedShape.startsWith("Zone") && client != null && client.level != null) {
            List<SelectedZoneRegistry.Zone> zones = SelectedZoneRegistry.snapshot(client.level.dimension());
            zoneCount = zones.size();
            if (!zones.isEmpty()) {
                SelectedZoneRegistry.Zone zone = zones.get(0);
                actualX = zone.max().getX() - zone.min().getX() + 1;
                actualY = zone.max().getY() - zone.min().getY() + 1;
                actualZ = zone.max().getZ() - zone.min().getZ() + 1;
            } else {
                actualX = width.intValue();
                actualY = height.intValue();
                actualZ = length.intValue();
            }
        } else if ("Floor".equals(selectedShape)) {
            actualX = width.intValue();
            actualY = 1;
            actualZ = length.intValue();
        } else if ("HollowBox".equals(selectedShape)) {
            actualX = width.intValue();
            actualY = height.intValue();
            actualZ = length.intValue();
        } else if ("Disc".equals(selectedShape) || "Ring".equals(selectedShape)) {
            actualX = radius.intValue() * 2 + 1;
            actualY = 1;
            actualZ = actualX;
        } else {
            actualX = radius.intValue() * 2 + 1;
            actualY = "Arena".equals(selectedShape) ? height.intValue() : actualX;
            actualZ = actualX;
        }

        List<PreviewVoxel> voxels = createPreviewVoxels(selectedShape, actualX, actualY, actualZ);
        String dimensions = actualX + " x " + actualY + " x " + actualZ;
        if (selectedShape.startsWith("Zone")) {
            dimensions += " / " + zoneCount + " zone" + (zoneCount == 1 ? "" : "s");
        }
        return new EditorPreview(stack, materialId, dimensions, voxels);
    }

    private List<PreviewVoxel> createPreviewVoxels(String selectedShape, int actualX, int actualY, int actualZ) {
        int maxActual = Math.max(1, Math.max(actualX, Math.max(actualY, actualZ)));
        double scale = Math.min(1.0D, 6.0D / maxActual);
        int sizeX = Math.max(1, (int)Math.round(actualX * scale));
        int sizeY = Math.max(1, (int)Math.round(actualY * scale));
        int sizeZ = Math.max(1, (int)Math.round(actualZ * scale));
        int shell = Math.max(1, (int)Math.ceil(thickness.intValue() * scale));
        LinkedHashSet<PreviewVoxel> output = new LinkedHashSet<>();

        if ("Disc".equals(selectedShape) || "Ring".equals(selectedShape)) {
            double centerX = (sizeX - 1) * 0.5D;
            double centerZ = (sizeZ - 1) * 0.5D;
            double radiusX = Math.max(0.5D, sizeX * 0.5D);
            double radiusZ = Math.max(0.5D, sizeZ * 0.5D);
            double inner = Math.max(0.0D, 1.0D - thickness.intValue() / (double)Math.max(1, radius.intValue()));
            for (int x = 0; x < sizeX; x++) {
                for (int z = 0; z < sizeZ; z++) {
                    double dx = (x - centerX) / radiusX;
                    double dz = (z - centerZ) / radiusZ;
                    double distance = dx * dx + dz * dz;
                    if (distance <= 1.0D && (!"Ring".equals(selectedShape) || distance >= inner * inner)) {
                        output.add(new PreviewVoxel(x, 0, z));
                    }
                }
            }
        } else if ("Sphere".equals(selectedShape) || "HollowSphere".equals(selectedShape)) {
            double centerX = (sizeX - 1) * 0.5D;
            double centerY = (sizeY - 1) * 0.5D;
            double centerZ = (sizeZ - 1) * 0.5D;
            double radiusX = Math.max(0.5D, sizeX * 0.5D);
            double radiusY = Math.max(0.5D, sizeY * 0.5D);
            double radiusZ = Math.max(0.5D, sizeZ * 0.5D);
            double inner = Math.max(0.0D, 1.0D - Math.max(1, shell) / (double)Math.max(1, Math.max(sizeX, sizeY)));
            for (int x = 0; x < sizeX; x++) {
                for (int y = 0; y < sizeY; y++) {
                    for (int z = 0; z < sizeZ; z++) {
                        double dx = (x - centerX) / radiusX;
                        double dy = (y - centerY) / radiusY;
                        double dz = (z - centerZ) / radiusZ;
                        double distance = dx * dx + dy * dy + dz * dz;
                        if (distance <= 1.0D && distance >= inner * inner) {
                            output.add(new PreviewVoxel(x, y, z));
                        }
                    }
                }
            }
        } else if ("Arena".equals(selectedShape)) {
            double centerX = (sizeX - 1) * 0.5D;
            double centerZ = (sizeZ - 1) * 0.5D;
            double radiusX = Math.max(0.5D, sizeX * 0.5D);
            double radiusZ = Math.max(0.5D, sizeZ * 0.5D);
            double inner = Math.max(0.0D, 1.0D - shell / (double)Math.max(1, Math.max(sizeX, sizeZ)));
            for (int x = 0; x < sizeX; x++) {
                for (int z = 0; z < sizeZ; z++) {
                    double dx = (x - centerX) / radiusX;
                    double dz = (z - centerZ) / radiusZ;
                    double distance = dx * dx + dz * dz;
                    if (distance <= 1.0D) {
                        output.add(new PreviewVoxel(x, 0, z));
                    }
                    if (distance <= 1.0D && distance >= inner * inner) {
                        for (int y = 1; y < sizeY; y++) {
                            output.add(new PreviewVoxel(x, y, z));
                        }
                    }
                }
            }
        } else {
            boolean floor = "Floor".equals(selectedShape);
            boolean wallsOnly = "ZoneWalls".equals(selectedShape);
            for (int x = 0; x < sizeX; x++) {
                for (int y = 0; y < sizeY; y++) {
                    for (int z = 0; z < sizeZ; z++) {
                        boolean xEdge = x < shell || sizeX - 1 - x < shell;
                        boolean yEdge = y < shell || sizeY - 1 - y < shell;
                        boolean zEdge = z < shell || sizeZ - 1 - z < shell;
                        boolean visibleSurface = xEdge || yEdge || zEdge;
                        if (floor ? y == 0 : wallsOnly ? xEdge || zEdge : visibleSurface) {
                            output.add(new PreviewVoxel(x, y, z));
                        }
                    }
                }
            }
        }
        return List.copyOf(output);
    }

    @Override
    public String description() {
        return "Plans and builds floors, boxes, circles, spheres, selected zones and a gated arena.";
    }

    @Override
    public String runtimeInfo(Minecraft client) {
        return "Builder shape=" + shape.choiceValue()
            + " anchor=" + anchor.choiceValue()
            + " state=" + buildState
            + " draft=" + draftState.name() + ":" + draftPositions.size()
            + " pending=" + pending.size() + "/" + plannedTotal
            + " confirmed=" + confirmed
            + " placed=" + lastPlaced
            + " blocked=" + blockedCycles
            + " material=" + plannedBlockId()
            + " autoMove=" + autoMove.displayValue()
            + " preview=" + preview.displayValue()
            + " player=" + (client != null && client.player != null
                ? String.format(Locale.ROOT, "%.1f/%.1f/%.1f", client.player.getX(), client.player.getY(), client.player.getZ())
                : "none");
    }

    private enum DraftState {
        OFF,
        LIVE,
        LOCKED
    }

    private record DraftContext(Block block, BlockPos anchor, String shape, String signature) {
    }

    private record StructureDraft(List<BlockPos> positions, Block block, BlockPos anchor, String shape, boolean truncated) {
    }

    public record EditorPreview(ItemStack material, String materialId, String dimensions, List<PreviewVoxel> voxels) {
    }

    public record PreviewVoxel(int x, int y, int z) {
    }
}
